include(CPM)

set(STDEXEC_BUILD_TESTS OFF)
set(STDEXEC_ENABLE_TESTING OFF)
set(STDEXEC_BUILD_EXAMPLES OFF)
set(STDEXEC_ENABLE_IO_URING ON)

set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
#

CPMAddPackage(
  NAME stdexec
  GITHUB_REPOSITORY NVIDIA/stdexec
  GIT_TAG main
)

