include(CPM)

set(STDEXEC_BUILD_TESTS OFF)
set(STDEXEC_ENABLE_TESTING OFF)
set(STDEXEC_BUILD_EXAMPLES OFF)
set(STDEXEC_ENABLE_IO_URING ON)

CPMAddPackage(
  NAME stdexec
  GITHUB_REPOSITORY NVIDIA/stdexec
  GIT_TAG main
)

