name: Update Dependencies

on:
  schedule: # Every week all sundays
    - cron: '0 0 * * 0'
  push:
    branches: 
      - '**'
    paths:
      - '.github/workflows/ci-dependencies.yml'
      - 'conanfile.py'
      - 'conan_install.py'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: conan-lock-global
  cancel-in-progress: false

jobs:
  sync-linux:
    name: Linux (${{ matrix.preset }})
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      fail-fast: false
      matrix:
        preset: [Debug-gcc, Release-gcc, Debug-clang, Release-clang, Sanitize-clang]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf -y update
          dnf -y install gcc clang python pip git cmake ninja-build

      - name: Configure Conan
        run: |
          python3 -m pip install jinja2 conan
          conan config install https://github.com/ch0pex/dotfiles.git --type git -sf .conan
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner
          conan remote enable conancenter

      - name: Build and Upload
        run: |
          ./conan_install.sh ${{ matrix.preset }}
          conan upload "*" -r monostudio-conan-local -c 

  sync-windows:
    name: Windows (${{ matrix.preset }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [Debug-msvc, Release-msvc]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Conan and Jinja2
        run: |
          PYTHON_BIN="C:/hostedtoolcache/windows/Python/3.14.3/x64"
          
          "$PYTHON_BIN/python3.exe" -m pip install --upgrade pip
          "$PYTHON_BIN/python3.exe" -m pip install conan jinja2
          
          echo "$PYTHON_BIN" >> $GITHUB_PATH
          echo "$PYTHON_BIN/Scripts" >> $GITHUB_PATH
          
          "$PYTHON_BIN/Scripts/conan.exe" config install https://github.com/ch0pex/dotfiles.git --type git -sf .conan
          "$PYTHON_BIN/Scripts/conan.exe" remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner
          "$PYTHON_BIN/Scripts/conan.exe" remote enable conancenter 
      - name: Build and Upload
        run: |
          chmod +x conan_install.sh
          ./conan_install.sh ${{ matrix.preset }}
          conan upload "*" -r monostudio-conan-local -c 

  collect-garbage: 
    name: Cleanup Remote
    runs-on: ubuntu-latest
    needs: [sync-linux, sync-windows]
    steps:
      - name: Configure Conan
        run: |
          python3 -m pip install jinja2 conan
          conan config install https://github.com/ch0pex/dotfiles.git --type git -sf .conan
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner
      - name: Collect Conan garbage
        run: |
          conan remove '*' -r monostudio-conan-local -lru=2w -c
          conan remove "*#~latest" -r monostudio-conan-local -c

