# shfmt: skip
name: Build and Test

on:
  push:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.gitattributes'
      - '.vscode/**'
      - "scripts/**"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  dependency_scan:
    name: Dependency scan
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, 'WIP') && 
      !contains(github.event.head_commit.message, 'wip')
    outputs:
      conan_changed: ${{ steps.changes.outputs.conan }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v4
        with:
          base: ${{ github.event.before }}
          filters: |
            conan:
              - 'conan/**'

  compile_dependencies_linux:
    name: Compile and upload dependencies - Linux
    needs: [ dependency_scan ]
    if: ${{ needs.dependency_scan.outputs.conan_changed == 'true' }}
    uses: ./.github/workflows/linux-dependencies.yml
    secrets: inherit

  compile_dependencies_windows:
    name: Compile and upload dependencies - Windows
    needs: [ dependency_scan ]
    if: ${{ needs.dependency_scan.outputs.conan_changed == 'true' }}
    uses: ./.github/workflows/windows-dependencies.yml
    secrets: inherit

  # -------------------------------------------------------------------
  # LINUX BUILDS (Fedora en Runner de GitHub)
  # -------------------------------------------------------------------
  linux-builds:
    name: Linux - ${{ matrix.preset }}
    needs: [ compile_dependencies_linux ]
    if: always() && (needs.compile_dependencies_linux.result == 'success' || needs.compile_dependencies_linux.result == 'skipped')
      && !contains(github.event.head_commit.message, 'WIP')
      && !contains(github.event.head_commit.message, 'wip')
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    strategy:
      fail-fast: false
      matrix:
        preset: [ Debug-gcc, Release-gcc, Debug-clang, Release-clang, Sanitize-gcc ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          dnf -y update
          dnf -y install git xorg-x11-server-Xvfb xkeyboard-config-devel ccache \
                         gcc gcc-c++ clang python3-pip cmake ninja-build valgrind \
                         texinfo libasan libubsan libubsan-static libasan-static compiler-rt
          python3 -m pip install conan jinja2

      - name: Configure Conan
        run: |
          conan config install conan/config
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner

      - name: Conan Install
        run: |
          chmod +x conan/install.sh
          ./conan/install.sh ${{ matrix.preset }}

      - name: Build
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}

      - name: Test (Xvfb)
        run: |
          xvfb-run -a --server-args="-screen 0 1280x1024x24" \
          ctest --preset ${{ matrix.preset }} -LE "graphics" --output-on-failure

      - name: Valgrind (Only on Debug)
        if: contains(matrix.preset, 'Debug')
        run: |
          COMPILER=$(echo ${{ matrix.preset }} | cut -d'-' -f2)
          xvfb-run -a --server-args="-screen 0 1280x1024x24" \
          ctest --test-dir build/$COMPILER/debug -T MemCheck -LE "graphics" --output-on-failure

  # -------------------------------------------------------------------
  # WINDOWS BUILDS (MSVC en Runner de GitHub)
  # -------------------------------------------------------------------
  windows-builds:
    name: Windows - ${{ matrix.preset }}
    needs: [ compile_dependencies_windows ]
    if: always() && (needs.compile_dependencies_windows.result == 'success' || needs.compile_dependencies_windows.result == 'skipped')
      && !contains(github.event.head_commit.message, 'WIP')
      && !contains(github.event.head_commit.message, 'wip')
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        preset: [ Debug-msvc, Release-msvc ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python & Conan
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        shell: bash
        run: pip install conan jinja2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure Conan
        shell: bash
        run: |
          conan config install conan/config
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner

      - name: Conan Install
        shell: bash
        run: |
          chmod +x conan/install.sh
          ./conan/install.sh ${{ matrix.preset }}

      - name: Build
        shell: bash
        run: |
          cmake --preset ${{ matrix.preset }}
          cmake --build --preset ${{ matrix.preset }}

      - name: Test
        shell: bash
        run: ctest --preset ${{ matrix.preset }} -LE "graphics|window" --output-on-failure
