name: Reusable Dependencies Sync

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync-linux:
    name: Linux (${{ matrix.preset }})
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      fail-fast: false
      matrix:
        preset: [Debug-gcc, Release-gcc, Debug-clang, Release-clang, Sanitize-gcc]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Linux build environment
        uses: ./.github/actions/setup-linux-build-env

      - name: Configure Conan
        run: |
          conan config install conan/config
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner
          conan remote enable conancenter

      - name: Build and Upload
        run: |
          chmod +x conan/install.sh
          ./conan/install.sh ${{ matrix.preset }}
          conan upload "*" -r monostudio-conan-local -c
