name: Reusable Dependencies Sync

on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  sync-windows:
    name: Windows (${{ matrix.preset }})
    if: ${{ !inputs.skip }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [Debug-msvc, Release-msvc]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # O la versión que necesites

      - name: Setup Conan and Jinja2
        run: |
          python -m pip install --upgrade pip
          python -m pip install conan jinja2
          
          # Los scripts como conan.exe ya estarán en el PATH automáticamente
          conan config install conan/config
          conan remote login -p "${{ secrets.CONAN_TOKEN }}" monostudio-conan-local runner
          conan remote enable conancenter

      - name: Build and Upload
        run: |
          chmod +x conan/install.sh
          ./conan/install.sh ${{ matrix.preset }}
          conan upload "*" -r monostudio-conan-local -c
